export enum BusinessChannelErrorCode {
  INVALID_EXTERNAL_ACCOUNT_ID = "CHANNEL_INVALID_EXTERNAL_ACCOUNT_ID",
  NOT_FOUND = "CHANNEL_CONNECTION_NOT_FOUND",
  ALREADY_CONNECTED_TO_ANOTHER_BUSINESS = "CHANNEL_ALREADY_CONNECTED_TO_ANOTHER_BUSINESS",
  BUSINESS_NOT_FOUND = "CHANNEL_BUSINESS_NOT_FOUND",
  META_CODE_EXCHANGE_FAILED = "CHANNEL_META_CODE_EXCHANGE_FAILED",
  META_WABA_SUBSCRIBE_FAILED = "CHANNEL_META_WABA_SUBSCRIBE_FAILED",
  META_PAGES_FETCH_FAILED = "CHANNEL_META_PAGES_FETCH_FAILED",
  META_PAGE_SUBSCRIBE_FAILED = "CHANNEL_META_PAGE_SUBSCRIBE_FAILED",
  META_NO_PAGES_FOUND = "CHANNEL_META_NO_PAGES_FOUND",
}