export enum BusinessChannelErrorCode {
  INVALID_EXTERNAL_ACCOUNT_ID = "CHANNEL_INVALID_EXTERNAL_ACCOUNT_ID",
  NOT_FOUND = "CHANNEL_CONNECTION_NOT_FOUND",
  ALREADY_CONNECTED_TO_ANOTHER_BUSINESS = "CHANNEL_ALREADY_CONNECTED_TO_ANOTHER_BUSINESS",
  BUSINESS_NOT_FOUND = "CHANNEL_BUSINESS_NOT_FOUND",
}
