export enum UserErrorCode {
  EMAIL_ALREADY_IN_USE = "USER_EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_TAKEN = "USER_USERNAME_ALREADY_TAKEN",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS",
  INVALID_EMAIL_FORMAT = "USER_INVALID_EMAIL_FORMAT",
  WEAK_PASSWORD = "USER_WEAK_PASSWORD",
  INVALID_USERNAME_FORMAT = "USER_INVALID_USERNAME_FORMAT",
}