export enum ServiceErrorCode {
  INVALID_NAME = "SERVICE_INVALID_NAME",
  INVALID_DURATION = "SERVICE_INVALID_DURATION",
  INVALID_PRICE = "SERVICE_INVALID_PRICE",
  DURATION_REQUIRED_FOR_FIXED = "SERVICE_DURATION_REQUIRED_FOR_FIXED",
  SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND",
  CANNOT_DELETE_LAST_SERVICE = "SERVICE_CANNOT_DELETE_LAST",
  MAX_SERVICES_REACHED= "SERVICE_MAX_SERVICES_REACHED",
}