export enum CloudinaryErrorCode {
  INVALID_FILE_TYPE = "CLOUDINARY_INVALID_FILE_TYPE",
  FILE_TOO_LARGE = "CLOUDINARY_FILE_TOO_LARGE",
  UPLOAD_FAILED = "CLOUDINARY_UPLOAD_FAILED",
  DELETE_FAILED = "CLOUDINARY_DELETE_FAILED",
}