export enum ScheduleErrorCode {
  INVALID_DAY = "SCHEDULE_INVALID_DAY",
  INVALID_TIME_FORMAT = "SCHEDULE_INVALID_TIME_FORMAT",
  END_BEFORE_START = "SCHEDULE_END_BEFORE_START",
  OVERLAPPING_SCHEDULE = "SCHEDULE_OVERLAPPING",
  SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND",
}
