export enum ReservationErrorCode {
  INVALID_TIME_RANGE = "RESERVATION_INVALID_TIME_RANGE",
  START_TIME_IN_PAST = "RESERVATION_START_TIME_IN_PAST",
  SLOT_TAKEN = "RESERVATION_SLOT_TAKEN",
  OUTSIDE_WORKING_HOURS = "RESERVATION_OUTSIDE_WORKING_HOURS",
  SERVICE_NOT_FOUND = "RESERVATION_SERVICE_NOT_FOUND",
  SERVICE_SELECTION_REQUIRED = "RESERVATION_SERVICE_SELECTION_REQUIRED",
  EMPLOYEE_NOT_FOUND = "RESERVATION_EMPLOYEE_NOT_FOUND",
  DURATION_REQUIRED = "RESERVATION_DURATION_REQUIRED",
  NOT_FOUND = "RESERVATION_NOT_FOUND",
  ALREADY_CANCELLED = "RESERVATION_ALREADY_CANCELLED",
  ALREADY_COMPLETED = "RESERVATION_ALREADY_COMPLETED",
  TOO_MANY_ACTIVE_RESERVATIONS = "RESERVATION_TOO_MANY_ACTIVE",
}