export enum GatewayErrorCode {
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE",
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}