export enum ResourceErrorCode {
  INVALID_NAME = "RESOURCE_INVALID_NAME",
  INVALID_CAPACITY = "RESOURCE_INVALID_CAPACITY",
  NOT_FOUND = "RESOURCE_NOT_FOUND",
  CANNOT_DELETE_LAST_RESOURCE = "RESOURCE_CANNOT_DELETE_LAST",
}
