export enum SubscriptionErrorCode {
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS = "SUBSCRIPTION_ALREADY_EXISTS",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
}
