export enum SubscriptionErrorCode {
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS = "SUBSCRIPTION_ALREADY_EXISTS",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",

  // Paddle webhook
  WEBHOOK_SIGNATURE_MISSING = "SUBSCRIPTION_WEBHOOK_SIGNATURE_MISSING",
  WEBHOOK_SIGNATURE_MALFORMED = "SUBSCRIPTION_WEBHOOK_SIGNATURE_MALFORMED",
  WEBHOOK_SIGNATURE_MISMATCH = "SUBSCRIPTION_WEBHOOK_SIGNATURE_MISMATCH",

  // Paddle checkout / plan change / cancel
  CANNOT_CHECKOUT_FREE_PLAN = "SUBSCRIPTION_CANNOT_CHECKOUT_FREE_PLAN",
  PLAN_MISSING_PADDLE_PRICE_ID = "SUBSCRIPTION_PLAN_MISSING_PADDLE_PRICE_ID",
  NOT_LINKED_TO_PADDLE = "SUBSCRIPTION_NOT_LINKED_TO_PADDLE",
  PADDLE_CHECKOUT_FAILED = "SUBSCRIPTION_PADDLE_CHECKOUT_FAILED",
  PADDLE_PLAN_CHANGE_FAILED = "SUBSCRIPTION_PADDLE_PLAN_CHANGE_FAILED",
  PADDLE_CANCEL_FAILED = "SUBSCRIPTION_PADDLE_CANCEL_FAILED",
}