export enum InvitationErrorCode {
  INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_USED = "INVITATION_ALREADY_USED",
  INVITATION_EXPIRED = "INVITATION_EXPIRED",
  INVITATION_ALREADY_PENDING = "INVITATION_ALREADY_PENDING",
  CANNOT_INVITE_AS_OWNER = "CANNOT_INVITE_AS_OWNER",
  CANNOT_INVITE_SELF = "CANNOT_INVITE_SELF",
  USER_ALREADY_MEMBER = "USER_ALREADY_MEMBER",
}