export enum ErrorCode {
  VALIDATION_FAILED = "VALIDATION_FAILED",

  FIELD_REQUIRED = "FIELD_REQUIRED",
  FIELD_INVALID_TYPE = "FIELD_INVALID_TYPE",
  FIELD_INVALID_EMAIL = "FIELD_INVALID_EMAIL",
  FIELD_MIN_LENGTH = "FIELD_MIN_LENGTH",
}
 