export enum ErrorCode {

  VALIDATION_FAILED = "VALIDATION_FAILED",

  FIELD_REQUIRED = "FIELD_REQUIRED",
  FIELD_INVALID_TYPE = "FIELD_INVALID_TYPE",
  FIELD_INVALID_EMAIL = "FIELD_INVALID_EMAIL",
  FIELD_MIN_LENGTH = "FIELD_MIN_LENGTH",

  USER_EMAIL_ALREADY_IN_USE = "USER_EMAIL_ALREADY_IN_USE",
  USER_USERNAME_ALREADY_TAKEN = "USER_USERNAME_ALREADY_TAKEN",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS",
  USER_WEAK_PASSWORD = "USER_WEAK_PASSWORD",

  BUSINESS_NOT_FOUND = "BUSINESS_NOT_FOUND",
}